import React, { useState, useRef } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Zap, Loader2, Download, RefreshCw, Mail, CheckCircle2, Send } from 'lucide-react';

const Digest: React.FC = () => {
  const [digest, setDigest] = useState('');
  const [generatedAt, setGeneratedAt] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const digestRef = useRef<HTMLDivElement>(null);

  // Download email gate
  const [downloadEmail, setDownloadEmail] = useState('');
  const [emailUnlocked, setEmailUnlocked] = useState(false);

  // Newsletter signup
  const [newsletterEmail, setNewsletterEmail] = useState('');
  const [newsletterSubmitting, setNewsletterSubmitting] = useState(false);
  const [newsletterSubmitted, setNewsletterSubmitted] = useState(false);

  const generateDigest = async () => {
    setLoading(true);
    setError('');
    setDigest('');
    setEmailUnlocked(false);

    try {
      const response = await fetch('/api/generate-digest', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({}),
      });

      if (!response.ok) {
        let message = 'Failed to generate digest';
        try {
          const data = await response.json();
          message = data.error || message;
        } catch {
          // Response wasn't JSON (e.g. local dev without serverless function)
        }
        throw new Error(message);
      }

      const text = await response.text();
      if (!text) throw new Error('Empty response from server');
      const data = JSON.parse(text);
      setDigest(data.digest);
      setGeneratedAt(data.generated_at);
    } catch (err: any) {
      setError(err.message || 'Something went wrong. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleDownloadUnlock = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!downloadEmail.trim()) return;

    // Send lead to webhook
    try {
      await fetch('https://services.leadconnectorhq.com/hooks/q4adJN1peFzHlHvxv37q/webhook-trigger/5f2a6926-db9d-45df-bc6f-2bc97f872458', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          email: downloadEmail,
          source: 'AI Intelligence Digest Download',
          submittedAt: new Date().toISOString(),
        }),
      });
    } catch {
      // Don't block download if webhook fails
    }

    setEmailUnlocked(true);
    triggerDownload();
  };

  const triggerDownload = () => {
    const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>AI Intelligence Digest — ${today}</title>
  <style>
    body { font-family: 'Georgia', serif; max-width: 700px; margin: 40px auto; padding: 20px; color: #1e293b; line-height: 1.8; }
    h1 { color: #0B4C83; border-bottom: 3px solid #00E5D1; padding-bottom: 16px; }
    h2 { color: #0B4C83; margin-top: 32px; }
    strong { color: #0B4C83; }
    hr { border: none; border-top: 1px solid #e2e8f0; margin: 32px 0; }
    .footer { text-align: center; color: #94a3b8; font-size: 12px; margin-top: 40px; }
    .footer a { color: #0B4C83; }
  </style>
</head>
<body>
  <h1>AI Intelligence Digest</h1>
  <p style="color: #64748b; font-size: 14px;">${today} — Generated by Vision Managers</p>
  ${digest.replace(/## /g, '<h2>').replace(/\n\n/g, '</p><p>').replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>').replace(/\n- /g, '<br>• ')}
  <div class="footer">
    <hr>
    <p>Generated by <a href="https://visionmanagers.com">Vision Managers</a> — Operational AI for High-Trust Businesses</p>
  </div>
</body>
</html>`;

    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `VM-Intelligence-Digest-${new Date().toISOString().split('T')[0]}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleNewsletter = async (e: React.FormEvent) => {
    e.preventDefault();
    setNewsletterSubmitting(true);
    try {
      const response = await fetch('https://services.leadconnectorhq.com/hooks/q4adJN1peFzHlHvxv37q/webhook-trigger/5f2a6926-db9d-45df-bc6f-2bc97f872458', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          email: newsletterEmail,
          source: 'AI Intelligence Digest Signup',
          submittedAt: new Date().toISOString(),
        }),
      });
      if (response.ok) setNewsletterSubmitted(true);
    } catch {
      // Silently fail
    } finally {
      setNewsletterSubmitting(false);
    }
  };

  // Simple markdown-to-HTML for the digest display
  const renderDigest = (text: string) => {
    return text
      .replace(/^## (.+)$/gm, '<h2 class="text-2xl font-serif text-vmNavy mt-10 mb-4">$1</h2>')
      .replace(/^### (.+)$/gm, '<h3 class="text-xl font-serif text-vmNavy mt-8 mb-3">$1</h3>')
      .replace(/\*\*(.+?)\*\*/g, '<strong class="text-vmNavy">$1</strong>')
      .replace(/\*(.+?)\*/g, '<em>$1</em>')
      .replace(/^- (.+)$/gm, '<li class="ml-4 mb-2">$1</li>')
      .replace(/(<li.*<\/li>\n?)+/g, '<ul class="list-disc pl-4 space-y-1 my-4">$&</ul>')
      .replace(/^---$/gm, '<hr class="my-8 border-slate-200" />')
      .replace(/\n\n/g, '</p><p class="mb-4 leading-relaxed">')
      .replace(/^(?!<[hul]|<li|<hr|<p)(.+)$/gm, '<p class="mb-4 leading-relaxed">$1</p>');
  };

  return (
    <div className="pt-40 pb-20 px-6 min-h-screen bg-white">
      <div className="max-w-4xl mx-auto">
        <Link to="/insights" className="inline-flex items-center gap-2 text-slate-400 hover:text-vmNavy transition-colors mb-12 text-xs font-bold uppercase tracking-widest">
          <ArrowLeft className="w-4 h-4" /> Back to Insights
        </Link>

        {/* Hero */}
        <header className="mb-16 text-center">
          <div className="w-16 h-16 bg-vmTeal/10 rounded-full flex items-center justify-center mx-auto mb-6">
            <Zap className="w-8 h-8 text-vmTeal" />
          </div>
          <span className="text-vmTeal font-black text-xs uppercase tracking-[0.3em] mb-4 block">AI-Powered Intelligence</span>
          <h1 className="text-5xl md:text-6xl font-serif text-vmNavy mb-8 leading-tight italic">Intelligence Digest.</h1>
          <p className="text-xl text-slate-500 font-light max-w-2xl mx-auto">
            Real-time executive briefing powered by AI web research. The latest AI developments analyzed through the lens of high-trust business operations.
          </p>
        </header>

        {/* Generate button (no email required) */}
        {!digest && !loading && !error && (
          <div className="max-w-lg mx-auto mb-20 text-center">
            <button
              onClick={generateDigest}
              className="inline-flex items-center gap-3 px-10 py-5 bg-vmNavy text-white font-bold uppercase tracking-widest text-xs rounded-sm hover:bg-vmTeal hover:text-vmNavy transition-all group"
            >
              <Zap className="w-5 h-5" /> Generate This Week's Digest
            </button>
            <p className="text-slate-400 text-sm mt-4">Takes 30-60 seconds. Powered by real-time AI web research.</p>
          </div>
        )}

        {/* Loading state */}
        {loading && (
          <div className="max-w-lg mx-auto mb-20">
            <div className="bg-vmSlate p-12 rounded-sm text-center">
              <div className="relative w-20 h-20 mx-auto mb-8">
                <div className="absolute inset-0 rounded-full border-2 border-vmTeal/20 animate-ping" />
                <div className="absolute inset-2 rounded-full border-2 border-vmTeal/40 animate-ping" style={{ animationDelay: '200ms' }} />
                <div className="absolute inset-0 rounded-full bg-vmNavy/5 flex items-center justify-center">
                  <Loader2 className="w-8 h-8 text-vmTeal animate-spin" />
                </div>
              </div>
              <h3 className="text-xl font-serif text-vmNavy mb-3 italic">Generating your digest...</h3>
              <p className="text-slate-400 text-sm">Searching the web and analyzing the latest AI developments. This may take 30-60 seconds.</p>
              <div className="mt-6 flex gap-1.5 h-2 items-center justify-center">
                {[...Array(12)].map((_, i) => (
                  <div key={i} className="w-1.5 h-full bg-vmTeal rounded-full animate-pulse" style={{ animationDelay: `${i * 100}ms` }} />
                ))}
              </div>
            </div>
          </div>
        )}

        {/* Error state */}
        {error && (
          <div className="max-w-lg mx-auto mb-20">
            <div className="bg-red-50 border border-red-200 p-8 rounded-sm text-center">
              <p className="text-red-700 mb-6">{error}</p>
              <button
                onClick={generateDigest}
                className="inline-flex items-center gap-2 px-6 py-3 bg-vmNavy text-white font-bold uppercase tracking-widest text-xs rounded-sm hover:bg-vmTeal hover:text-vmNavy transition-all"
              >
                <RefreshCw className="w-4 h-4" /> Try Again
              </button>
            </div>
          </div>
        )}

        {/* Digest display */}
        {digest && (
          <>
            <div ref={digestRef} className="mb-12">
              <div className="flex items-center justify-between mb-8">
                <div>
                  <span className="text-vmTeal font-black text-[10px] uppercase tracking-widest block mb-1">Generated Report</span>
                  {generatedAt && (
                    <span className="text-xs text-slate-400">
                      {new Date(generatedAt).toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
                    </span>
                  )}
                </div>
                <button
                  onClick={generateDigest}
                  className="inline-flex items-center gap-2 px-4 py-2 border border-slate-200 text-slate-500 font-bold uppercase tracking-widest text-[10px] rounded-sm hover:border-vmTeal hover:text-vmNavy transition-all"
                >
                  <RefreshCw className="w-3 h-3" /> Regenerate
                </button>
              </div>

              <div
                className="bg-white border border-slate-200 rounded-sm p-8 md:p-12 text-slate-700 leading-relaxed font-light"
                dangerouslySetInnerHTML={{ __html: renderDigest(digest) }}
              />
            </div>

            {/* Download gate — email required to download */}
            <div className="mb-12 p-8 bg-vmSlate rounded-sm">
              {emailUnlocked ? (
                <div className="text-center">
                  <CheckCircle2 className="w-10 h-10 text-vmTeal mx-auto mb-3" />
                  <p className="text-vmNavy font-serif text-lg mb-4">Report downloaded.</p>
                  <button
                    onClick={triggerDownload}
                    className="inline-flex items-center gap-2 text-vmNavy font-bold text-xs uppercase tracking-widest hover:text-vmTeal transition-colors"
                  >
                    <Download className="w-4 h-4" /> Download Again
                  </button>
                </div>
              ) : (
                <div className="text-center">
                  <Download className="w-8 h-8 text-vmTeal mx-auto mb-4" />
                  <h3 className="text-xl font-serif text-vmNavy mb-2">Download this report</h3>
                  <p className="text-slate-500 text-sm mb-6">Enter your email to download the formatted HTML report.</p>
                  <form onSubmit={handleDownloadUnlock} className="flex flex-col sm:flex-row gap-3 max-w-md mx-auto">
                    <input
                      required
                      type="email"
                      placeholder="executive@company.com"
                      className="flex-grow p-4 border border-slate-200 outline-none focus:border-vmTeal rounded-sm text-sm"
                      value={downloadEmail}
                      onChange={(e) => setDownloadEmail(e.target.value)}
                    />
                    <button
                      type="submit"
                      className="px-8 py-4 bg-vmNavy text-white font-bold uppercase tracking-widest text-[10px] rounded-sm hover:bg-vmTeal hover:text-vmNavy transition-all flex items-center justify-center gap-2"
                    >
                      <Download className="w-4 h-4" /> Download
                    </button>
                  </form>
                </div>
              )}
            </div>

            {/* Newsletter signup */}
            <section className="p-12 bg-vmSlate rounded-sm text-center">
              <h3 className="text-2xl font-serif text-vmNavy mb-4">Get the digest weekly.</h3>
              <p className="text-slate-500 mb-8 max-w-lg mx-auto text-sm">Subscribe to receive the AI Intelligence Digest in your inbox every Monday.</p>

              {newsletterSubmitted ? (
                <div className="flex flex-col items-center gap-3">
                  <CheckCircle2 className="w-10 h-10 text-vmTeal" />
                  <p className="text-vmNavy font-serif text-lg">Subscribed.</p>
                </div>
              ) : (
                <form onSubmit={handleNewsletter} className="flex flex-col sm:flex-row gap-3 max-w-md mx-auto">
                  <input
                    required
                    type="email"
                    placeholder="executive@company.com"
                    className="flex-grow p-4 border border-slate-200 outline-none focus:border-vmTeal rounded-sm text-sm"
                    value={newsletterEmail}
                    onChange={(e) => setNewsletterEmail(e.target.value)}
                  />
                  <button
                    disabled={newsletterSubmitting}
                    className="px-8 py-4 bg-vmNavy text-white font-bold uppercase tracking-widest text-[10px] rounded-sm hover:bg-vmTeal hover:text-vmNavy transition-all flex items-center justify-center gap-2"
                  >
                    {newsletterSubmitting ? <Loader2 className="w-4 h-4 animate-spin" /> : <><Send className="w-3 h-3" /> Subscribe</>}
                  </button>
                </form>
              )}
            </section>
          </>
        )}
      </div>
    </div>
  );
};

export default Digest;
